>-  # Pandas Library:

In [170]:
import pandas as pd
import numpy as np

In [14]:
Series1=pd.Series([1,2,3])

In [15]:
Series1

0    1
1    2
2    3
dtype: int64

In [11]:
Series2=pd.Series([4,5,6],index=['a','b','c'])
Series2

a    4
b    5
c    6
dtype: int64

In [12]:
Series3=pd.Series([4,5,6])
Series3

0    4
1    5
2    6
dtype: int64

In [17]:
DF=pd.DataFrame({ 'Col1' : Series1 , 'Col2' : Series3})
DF

   Col1  Col2
0     1     4
1     2     5
2     3     6

In [18]:
Data={
    'A':[1,2,3,4,5],
    'B':['A','B','C','D','E']
}
DF2=pd.DataFrame(Data)
DF2

   A  B
0  1  A
1  2  B
2  3  C
3  4  D
4  5  E

In [24]:
DF3=pd.read_excel('car-sales.xlsx')
DF3

     Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White         150043      4   4000
1   Honda    Red          87899      4   5000
2  Toyota   Blue          32549      3   7000
3     BMW  Black          11179      5  22000
4  Nissan  White         213095      4   3500
5  Toyota  Green          99213      4   4500
6   Honda   Blue          45698      4   7500
7   Honda   Blue          54738      4   7000
8  Toyota  White          60000      4   6250
9  Nissan  White          31600      4   9700

In [25]:
DF3.head()

     Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White         150043      4   4000
1   Honda    Red          87899      4   5000
2  Toyota   Blue          32549      3   7000
3     BMW  Black          11179      5  22000
4  Nissan  White         213095      4   3500

In [26]:
DF3.tail()

     Make Colour  Odometer (KM)  Doors  Price
5  Toyota  Green          99213      4   4500
6   Honda   Blue          45698      4   7500
7   Honda   Blue          54738      4   7000
8  Toyota  White          60000      4   6250
9  Nissan  White          31600      4   9700

In [27]:
DF3.describe()

       Odometer (KM)      Doors         Price
count      10.000000  10.000000     10.000000
mean    78601.400000   4.000000   7645.000000
std     61983.471735   0.471405   5379.407753
min     11179.000000   3.000000   3500.000000
25%     35836.250000   4.000000   4625.000000
50%     57369.000000   4.000000   6625.000000
75%     96384.500000   4.000000   7375.000000
max    213095.000000   5.000000  22000.000000

In [28]:
DF3.describe(include='all')

          Make Colour  Odometer (KM)      Doors         Price
count       10     10      10.000000  10.000000     10.000000
unique       4      5            NaN        NaN           NaN
top     Toyota  White            NaN        NaN           NaN
freq         4      4            NaN        NaN           NaN
mean       NaN    NaN   78601.400000   4.000000   7645.000000
std        NaN    NaN   61983.471735   0.471405   5379.407753
min        NaN    NaN   11179.000000   3.000000   3500.000000
25%        NaN    NaN   35836.250000   4.000000   4625.000000
50%        NaN    NaN   57369.000000   4.000000   6625.000000
75%        NaN    NaN   96384.500000   4.000000   7375.000000
max        NaN    NaN  213095.000000   5.000000  22000.000000

In [29]:
DF3.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [30]:
DF3.values

array([['Toyota', 'White', 150043, 4, 4000],
       ['Honda', 'Red', 87899, 4, 5000],
       ['Toyota', 'Blue', 32549, 3, 7000],
       ['BMW', 'Black', 11179, 5, 22000],
       ['Nissan', 'White', 213095, 4, 3500],
       ['Toyota', 'Green', 99213, 4, 4500],
       ['Honda', 'Blue', 45698, 4, 7500],
       ['Honda', 'Blue', 54738, 4, 7000],
       ['Toyota', 'White', 60000, 4, 6250],
       ['Nissan', 'White', 31600, 4, 9700]], dtype=object)

In [31]:
DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    3 non-null      int64
 1   Col2    3 non-null      int64
dtypes: int64(2)
memory usage: 176.0 bytes

In [32]:
DF3.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [33]:
DF3.count()

Make             10
Colour           10
Odometer (KM)    10
Doors            10
Price            10
dtype: int64

In [35]:
DF3.value_counts()

Make    Colour  Odometer (KM)  Doors  Price
BMW     Black   11179          5      22000    1
Honda   Blue    45698          4      7500     1
                54738          4      7000     1
        Red     87899          4      5000     1
Nissan  White   31600          4      9700     1
                213095         4      3500     1
Toyota  Blue    32549          3      7000     1
        Green   99213          4      4500     1
        White   60000          4      6250     1
                150043         4      4000     1
Name: count, dtype: int64

In [38]:
DF4=pd.read_excel('carMissingData.xlsx')
DF4

     Make Colour  Odometer (KM)  Doors    Price
0  Toyota  White       150043.0      4   4000.0
1   Honda    NaN        87899.0      4   5000.0
2  Toyota   Blue            NaN      3   7000.0
3     BMW  Black        11179.0      5  22000.0
4  Nissan  White       213095.0      4   3500.0
5  Toyota  Green        99213.0      4   4500.0
6   Honda    NaN            NaN      4   7500.0
7   Honda   Blue        54738.0      4      NaN
8  Toyota  White        60000.0      4   6250.0
9  Nissan  White        31600.0      4   9700.0

In [39]:
DF4.value_counts()

Make    Colour  Odometer (KM)  Doors  Price
BMW     Black   11179.0        5      22000.0    1
Nissan  White   31600.0        4      9700.0     1
                213095.0       4      3500.0     1
Toyota  Green   99213.0        4      4500.0     1
        White   60000.0        4      6250.0     1
                150043.0       4      4000.0     1
Name: count, dtype: int64

In [40]:
DF4.value_counts(dropna=False,normalize=True)

Make    Colour  Odometer (KM)  Doors  Price
BMW     Black   11179.0        5      22000.0    0.1
Honda   Blue    54738.0        4      NaN        0.1
        NaN     87899.0        4      5000.0     0.1
                NaN            4      7500.0     0.1
Nissan  White   31600.0        4      9700.0     0.1
                213095.0       4      3500.0     0.1
Toyota  Blue    NaN            3      7000.0     0.1
        Green   99213.0        4      4500.0     0.1
        White   60000.0        4      6250.0     0.1
                150043.0       4      4000.0     0.1
Name: proportion, dtype: float64

In [41]:
DF3.memory_usage()

Index            128
Make              80
Colour            80
Odometer (KM)     80
Doors             80
Price             80
dtype: int64

In [42]:
DF4.value_counts()

Make    Colour  Odometer (KM)  Doors  Price
BMW     Black   11179.0        5      22000.0    1
Nissan  White   31600.0        4      9700.0     1
                213095.0       4      3500.0     1
Toyota  Green   99213.0        4      4500.0     1
        White   60000.0        4      6250.0     1
                150043.0       4      4000.0     1
Name: count, dtype: int64

In [43]:
DF4.shape

(10, 5)

In [45]:
DF4.size

50

In [46]:
DF4.count()

Make             10
Colour            8
Odometer (KM)     8
Doors            10
Price             9
dtype: int64

In [47]:
DF3.count()

Make             10
Colour           10
Odometer (KM)    10
Doors            10
Price            10
dtype: int64

In [48]:
DF3.nunique()

Make              4
Colour            5
Odometer (KM)    10
Doors             3
Price             9
dtype: int64

In [49]:
DF3

     Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White         150043      4   4000
1   Honda    Red          87899      4   5000
2  Toyota   Blue          32549      3   7000
3     BMW  Black          11179      5  22000
4  Nissan  White         213095      4   3500
5  Toyota  Green          99213      4   4500
6   Honda   Blue          45698      4   7500
7   Honda   Blue          54738      4   7000
8  Toyota  White          60000      4   6250
9  Nissan  White          31600      4   9700

In [55]:
DF3.to_csv('NewCarCSV.csv',index=False)

In [53]:
DF5=pd.read_csv('NewCarCSV.csv')
DF5

     Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White         150043      4   4000
1   Honda    Red          87899      4   5000
2  Toyota   Blue          32549      3   7000
3     BMW  Black          11179      5  22000
4  Nissan  White         213095      4   3500
5  Toyota  Green          99213      4   4500
6   Honda   Blue          45698      4   7500
7   Honda   Blue          54738      4   7000
8  Toyota  White          60000      4   6250
9  Nissan  White          31600      4   9700

In [56]:
DF5.Make

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: object

In [59]:
DF5.sample(5)

     Make Colour  Odometer (KM)  Doors  Price
5  Toyota  Green          99213      4   4500
7   Honda   Blue          54738      4   7000
6   Honda   Blue          45698      4   7500
2  Toyota   Blue          32549      3   7000
1   Honda    Red          87899      4   5000

In [60]:
DF5.loc[0]

Make             Toyota
Colour            White
Odometer (KM)    150043
Doors                 4
Price              4000
Name: 0, dtype: object

In [64]:
DF5.loc[0,'Make']

'Toyota'

In [66]:
DF5.iloc[:,0]

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: object

In [67]:
DF5.iloc[0]

Make             Toyota
Colour            White
Odometer (KM)    150043
Doors                 4
Price              4000
Name: 0, dtype: object

In [74]:
DF5.iloc[0,0]

'Toyota'

In [78]:
DF5.columns.get_loc('Odometer (KM)')

2

In [84]:
DF5.duplicated(keep='first')

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [85]:
DF5.duplicated(keep='last')

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [86]:
DF5.duplicated(subset=['Make'],keep='first')

0    False
1    False
2     True
3    False
4    False
5     True
6     True
7     True
8     True
9     True
dtype: bool

In [87]:
DF5.duplicated(subset=['Make'],keep='last')

0     True
1     True
2     True
3    False
4     True
5     True
6     True
7    False
8    False
9    False
dtype: bool

In [89]:
DF5.duplicated().any().sum()

0

In [90]:
DF5['Make'].duplicated().any()

True

In [91]:
DF5['Make'].duplicated()

0    False
1    False
2     True
3    False
4    False
5     True
6     True
7     True
8     True
9     True
Name: Make, dtype: bool

In [92]:
DF5['Make'].duplicated().sum()

6

In [115]:
DF5.duplicated(keep=False)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [116]:
DF5.duplicated(keep=False).any()

False

In [93]:
DF5.sample(frac=0.5)

     Make Colour  Odometer (KM)  Doors  Price
6   Honda   Blue          45698      4   7500
5  Toyota  Green          99213      4   4500
2  Toyota   Blue          32549      3   7000
3     BMW  Black          11179      5  22000
7   Honda   Blue          54738      4   7000

In [94]:
DF5.sample(frac=1)

     Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White         150043      4   4000
8  Toyota  White          60000      4   6250
9  Nissan  White          31600      4   9700
2  Toyota   Blue          32549      3   7000
5  Toyota  Green          99213      4   4500
4  Nissan  White         213095      4   3500
7   Honda   Blue          54738      4   7000
1   Honda    Red          87899      4   5000
3     BMW  Black          11179      5  22000
6   Honda   Blue          45698      4   7500

In [159]:
DF5.max()

Make             Toyota
Colour            White
Odometer (KM)    213095
Doors                 5
Price             22000
dtype: object

In [160]:
DF5.min()

Make               BMW
Colour           Black
Odometer (KM)    11179
Doors                3
Price             3500
dtype: object

In [162]:
DF5.idxmax()

Make             0
Colour           0
Odometer (KM)    4
Doors            3
Price            3
dtype: int64

In [164]:
Series3

0    4
1    5
2    6
dtype: int64

In [165]:
Series3.idxmax()

2

In [167]:
Series3.max()

6

In [105]:
DF5['Make'].drop_duplicates()

0    Toyota
1     Honda
3       BMW
4    Nissan
Name: Make, dtype: object

In [109]:
DF5.drop_duplicates().any()

Make             True
Colour           True
Odometer (KM)    True
Doors            True
Price            True
dtype: bool

In [110]:
DF5

     Make Colour  Odometer (KM)  Doors  Price
0  Toyota  White         150043      4   4000
1   Honda    Red          87899      4   5000
2  Toyota   Blue          32549      3   7000
3     BMW  Black          11179      5  22000
4  Nissan  White         213095      4   3500
5  Toyota  Green          99213      4   4500
6   Honda   Blue          45698      4   7500
7   Honda   Blue          54738      4   7000
8  Toyota  White          60000      4   6250
9  Nissan  White          31600      4   9700

In [118]:
pd.crosstab(DF5['Make'],DF5['Doors'])

Doors   3  4  5
Make
BMW     0  0  1
Honda   0  3  0
Nissan  0  2  0
Toyota  1  3  0

In [122]:
DF

   Col1  Col2
0     1     4
1     2     5
2     3     6

In [123]:
DF['Col3'] = [7,8,9]

In [124]:
DF

   Col1  Col2  Col3
0     1     4     7
1     2     5     8
2     3     6     9

In [125]:
DF4

     Make Colour  Odometer (KM)  Doors    Price
0  Toyota  White       150043.0      4   4000.0
1   Honda    NaN        87899.0      4   5000.0
2  Toyota   Blue            NaN      3   7000.0
3     BMW  Black        11179.0      5  22000.0
4  Nissan  White       213095.0      4   3500.0
5  Toyota  Green        99213.0      4   4500.0
6   Honda    NaN            NaN      4   7500.0
7   Honda   Blue        54738.0      4      NaN
8  Toyota  White        60000.0      4   6250.0
9  Nissan  White        31600.0      4   9700.0

In [132]:
DF4['Colour'].str.contains('White',na='NaN')

0     True
1      NaN
2    False
3    False
4     True
5    False
6      NaN
7    False
8     True
9     True
Name: Colour, dtype: object

In [133]:
DF4['Colour'].str.contains('White')

0     True
1      NaN
2    False
3    False
4     True
5    False
6      NaN
7    False
8     True
9     True
Name: Colour, dtype: object

In [134]:
Unique_Make=DF4['Make'].dropna().unique()

In [135]:
Unique_Make

array(['Toyota', 'Honda', 'BMW', 'Nissan'], dtype=object)

In [137]:
DF4

     Make Colour  Odometer (KM)  Doors    Price
0  Toyota  White       150043.0      4   4000.0
1   Honda    NaN        87899.0      4   5000.0
2  Toyota   Blue            NaN      3   7000.0
3     BMW  Black        11179.0      5  22000.0
4  Nissan  White       213095.0      4   3500.0
5  Toyota  Green        99213.0      4   4500.0
6   Honda    NaN            NaN      4   7500.0
7   Honda   Blue        54738.0      4      NaN
8  Toyota  White        60000.0      4   6250.0
9  Nissan  White        31600.0      4   9700.0

In [138]:
DF4.dropna(subset=['Colour','Odometer (KM)','Price'],axis=0,how='any')

     Make Colour  Odometer (KM)  Doors    Price
0  Toyota  White       150043.0      4   4000.0
3     BMW  Black        11179.0      5  22000.0
4  Nissan  White       213095.0      4   3500.0
5  Toyota  Green        99213.0      4   4500.0
8  Toyota  White        60000.0      4   6250.0
9  Nissan  White        31600.0      4   9700.0

In [143]:
DF4['Odometer (KM)'].fillna(value=DF4['Odometer (KM)'].mean(),axis=0,limit=None,inplace=True)

In [144]:
DF4

     Make Colour  Odometer (KM)  Doors    Price
0  Toyota  White     150043.000      4   4000.0
1   Honda    NaN      87899.000      4   5000.0
2  Toyota   Blue      88470.875      3   7000.0
3     BMW  Black      11179.000      5  22000.0
4  Nissan  White     213095.000      4   3500.0
5  Toyota  Green      99213.000      4   4500.0
6   Honda    NaN      88470.875      4   7500.0
7   Honda   Blue      54738.000      4      NaN
8  Toyota  White      60000.000      4   6250.0
9  Nissan  White      31600.000      4   9700.0

In [150]:
DF4['Price'].fillna(method='ffill',inplace=True)

C:\Users\Waleed Abdullah\AppData\Local\Temp\ipykernel_37420\2101046110.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  DF4['Price'].fillna(method='bfill',inplace=True)
C:\Users\Waleed Abdullah\AppData\Local\Temp\ipykernel_37420\2101046110.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  DF4['Price'].fillna(method='bfill',inplace=True)

In [151]:
DF4

     Make Colour  Odometer (KM)  Doors    Price
0  Toyota  White     150043.000      4   4000.0
1   Honda    NaN      87899.000      4   5000.0
2  Toyota   Blue      88470.875      3   7000.0
3     BMW  Black      11179.000      5  22000.0
4  Nissan  White     213095.000      4   3500.0
5  Toyota  Green      99213.000      4   4500.0
6   Honda    NaN      88470.875      4   7500.0
7   Honda   Blue      54738.000      4   7500.0
8  Toyota  White      60000.000      4   6250.0
9  Nissan  White      31600.000      4   9700.0

In [152]:
Numerical_Cols=DF5.select_dtypes(include=['int64','float64']).columns
Categorical_Cols=DF5.select_dtypes(include=['object']).columns

In [153]:
Numerical_Cols

Index(['Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [154]:
Categorical_Cols

Index(['Make', 'Colour'], dtype='object')

In [155]:
Correlation_Matrix=DF5[Numerical_Cols].corr()

In [156]:
Correlation_Matrix

               Odometer (KM)     Doors     Price
Odometer (KM)       1.000000 -0.081263 -0.631781
Doors              -0.081263  1.000000  0.657235
Price              -0.631781  0.657235  1.000000

In [157]:
Absolute_Vals=Correlation_Matrix.abs()

In [158]:
Absolute_Vals

               Odometer (KM)     Doors     Price
Odometer (KM)       1.000000  0.081263  0.631781
Doors               0.081263  1.000000  0.657235
Price               0.631781  0.657235  1.000000

In [172]:
np.fill_diagonal(Absolute_Vals.values,0)

In [173]:
Absolute_Vals

               Odometer (KM)     Doors     Price
Odometer (KM)       0.000000  0.081263  0.631781
Doors               0.081263  0.000000  0.657235
Price               0.631781  0.657235  0.000000

In [174]:
Absolute_Vals.idxmax()

Odometer (KM)    Price
Doors            Price
Price            Doors
dtype: object

In [175]:
Absolute_Vals.max()

Odometer (KM)    0.631781
Doors            0.657235
Price            0.657235
dtype: float64

In [176]:
Absolute_Vals.unstack().idxmax()

('Doors', 'Price')

In [177]:
Absolute_Vals.unstack().max()

0.6572347864263308